## 1. Numpy 기본 - 각 3점씩

In [1]:
import numpy as np

#### 1) 0에서부터 29까지의 숫자가 순서대로 들어간 3x10 matrix를 만들어 보시오. 최종 결과물은 아래와 같습니다 

In [12]:
g=np.arange(30)

In [15]:
g.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#### 2) 1)에서 생성한 array의 모든 element에 10을 곱한 후 5를 더한 새로운 array를 생성히시오

In [20]:
g2=g*10
g2=g2+5
g2

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125,
       135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255,
       265, 275, 285, 295])

#### 3) 1)에서 생성한 array에서 10보다 크거나 같은 모든 원소들을 999로 변환하는 코드를 작성하시오


In [26]:
g2[g2<10]=999
g2

array([999,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125,
       135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255,
       265, 275, 285, 295])

#### 4) numpy 라이브러리를 사용하여 다음 두 개의 배열을 수직 방향(axis=0)과 수평 방향(axis=1)으로 연결하세요.

In [3]:
arr1=np.array([[1,2,3],
              [4,5,6]])

arr2=np.array([[7,8,9],
              [10,11,12]])

1. 수직방향 연결

In [30]:
arr3=np.vstack((arr1,arr2))
arr3


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

2. 수평방향 연결

In [32]:
arr4=np.hstack((arr1,arr2))
arr4

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## 2. Pandas 기본 - 각 3점씩

In [33]:
import pandas as pd

#### 1) 다음은 미국 프로농구 NBA 리그 선수들의 나이, 키, 소속팀 지역(서부/동부), 20년 평균득점, 21년 평균득점, 20년 평균어시스트, 21년 평균어시스트를 나타낸 것이다. Dictionary 형태로 되어 있는 것을 각 key값을 column으로 하는 데이터 프레임으로 변환하시오

In [47]:
nba_data = {
    "age": {
        "Lebron": 38, "Durant": 34, "Curry": 34, "Harden": 33, "Westbrook": 34,
        "Lillard": 32, "Antetokounmpo": 28, "Jokic": 27, "Irving": 30, "Doncic": 23,
        "Embiid": 28, "George": 32, "Tatum": 24, "Butler": 32, "Mitchell": 25,
        "Gobert": 30, "Booker": 25, "Paul": 37, "Bam": 25, "Simmons": 26
    },
    "height": {
        "Lebron": 206, "Durant": 208, "Curry": 191, "Harden": 196, "Westbrook": 191,
        "Lillard": 191, "Antetokounmpo": 211, "Jokic": 213, "Irving": 188, "Doncic": 201,
        "Embiid": 213, "George": 203, "Tatum": 203, "Butler": 201, "Mitchell": 185,
        "Gobert": 216, "Booker": 198, "Paul": 183, "Bam": 206, "Simmons": 208
    },
    "team_region": {
        "Durant": "Eastern", "Curry": "Western", "Harden": "Eastern", "Westbrook": "Eastern",
        "Lillard": "Western", "Antetokounmpo": "Eastern", "Jokic": "Western", "Irving": "Eastern", "Doncic": "Western",
        "Embiid": "Eastern", "George": "Western", "Tatum": "Eastern", "Butler": "Eastern", "Mitchell": "Western",
        "Gobert": "Western", "Booker": "Western", "Paul": "Western", "Bam": "Eastern", "Simmons": "Eastern"
    },
    "ppg_20": {
        "Lebron": 25.3, "Durant": 26.0, "Curry": 32.0, "Harden": 24.6, "Westbrook": 22.2,
        "Lillard": 28.8, "Antetokounmpo": 28.1, "Jokic": 26.4, "Irving": 27.0, "Doncic": 27.7,
        "Embiid": 28.5, "George": 23.3, "Tatum": 26.4, "Butler": 21.5, "Mitchell": 26.4,
        "Gobert": 14.3, "Booker": 25.6, "Paul": 16.4, "Bam": 18.7, "Simmons": 14.3
    },
    "ppg_21": {
        "Lebron": 26.2, "Durant": 27.1, "Curry": 31.0, "Harden": 23.4, "Westbrook": 21.9,
        "Lillard": 27.7, "Antetokounmpo": 29.0, "Jokic": 26.9, "Irving": 26.3, "Doncic": 28.6,
        "Embiid": 28.9, "George": 24.5, "Tatum": 25.7, "Butler": 22.1, "Mitchell": 25.8,
        "Gobert": 15.1, "Booker": 24.8, "Paul": 15.3, "Bam": 19.2, "Simmons": 13.9
        },
    "apg_20": {
        "Lebron": 10.2, "Durant": 5.9, "Curry": 5.8, "Harden": 10.9, "Westbrook": 11.7,
        "Lillard": 7.8, "Antetokounmpo": 5.6, "Jokic": 8.3, "Irving": 6.1, "Doncic": 8.6,
        "Embiid": 3.0, "George": 5.2, "Tatum": 4.3, "Butler": 6.0, "Mitchell": 4.8,
        "Gobert": 2.0, "Booker": 6.5, "Paul": 9.3, "Bam": 5.1, "Simmons": 8.0
        },
    "apg_21": {
        "Lebron": 9.8, "Durant": 6.2, "Curry": 6.1, "Harden": 9.7, "Westbrook": 11.5,
        "Lillard": 7.5, "Antetokounmpo": 5.9, "Jokic": 8.8, "Irving": 5.9, "Doncic": 9.0,
        "Embiid": 3.1, "George": 5.4, "Tatum": 4.6, "Butler": 6.2, "Mitchell": 5.1,
        "Gobert": 2.3, "Booker": 6.2, "Paul": 8.7, "Bam": 5.5, "Simmons": 7.7
        }
    }
       

In [48]:
nba_data.keys()

dict_keys(['age', 'height', 'team_region', 'ppg_20', 'ppg_21', 'apg_20', 'apg_21'])

In [49]:
people = pd.DataFrame(nba_data)
people

age  height team_region  ppg_20  ppg_21  apg_20  apg_21
Lebron          38     206         NaN    25.3    26.2    10.2     9.8
Durant          34     208     Eastern    26.0    27.1     5.9     6.2
Curry           34     191     Western    32.0    31.0     5.8     6.1
Harden          33     196     Eastern    24.6    23.4    10.9     9.7
Westbrook       34     191     Eastern    22.2    21.9    11.7    11.5
Lillard         32     191     Western    28.8    27.7     7.8     7.5
Antetokounmpo   28     211     Eastern    28.1    29.0     5.6     5.9
Jokic           27     213     Western    26.4    26.9     8.3     8.8
Irving          30     188     Eastern    27.0    26.3     6.1     5.9
Doncic          23     201     Western    27.7    28.6     8.6     9.0
Embiid          28     213     Eastern    28.5    28.9     3.0     3.1
George          32     203     Western    23.3    24.5     5.2     5.4
Tatum           24     203     Eastern    26.4    25.7     4.3     4.6
Butler          32     201     Eastern    21.5    22.1     6.0     6.2
Mitchell        25     185     Western    26.4    25.8     4.8     5.1
Gobert          30     216     Western    14.3    15.1     2.0     2.3
Booker          25     198     Western    25.6    24.8     6.5     6.2
Paul            37     183     Western    16.4    15.3     9.3     8.7
Bam             25     206     Eastern    18.7    19.2     5.1     5.5
Simmons         26     208     Eastern    14.3    13.9     8.0     7.7

#### 2) Lebron의 team_region 값이 'Western'라고 할 때 해당 값을 위의 데이터 프레임에 추가하시오

In [50]:
people.iloc[0,2]='Western'
people

age  height team_region  ppg_20  ppg_21  apg_20  apg_21
Lebron          38     206     Western    25.3    26.2    10.2     9.8
Durant          34     208     Eastern    26.0    27.1     5.9     6.2
Curry           34     191     Western    32.0    31.0     5.8     6.1
Harden          33     196     Eastern    24.6    23.4    10.9     9.7
Westbrook       34     191     Eastern    22.2    21.9    11.7    11.5
Lillard         32     191     Western    28.8    27.7     7.8     7.5
Antetokounmpo   28     211     Eastern    28.1    29.0     5.6     5.9
Jokic           27     213     Western    26.4    26.9     8.3     8.8
Irving          30     188     Eastern    27.0    26.3     6.1     5.9
Doncic          23     201     Western    27.7    28.6     8.6     9.0
Embiid          28     213     Eastern    28.5    28.9     3.0     3.1
George          32     203     Western    23.3    24.5     5.2     5.4
Tatum           24     203     Eastern    26.4    25.7     4.3     4.6
Butler          32     201     Eastern    21.5    22.1     6.0     6.2
Mitchell        25     185     Western    26.4    25.8     4.8     5.1
Gobert          30     216     Western    14.3    15.1     2.0     2.3
Booker          25     198     Western    25.6    24.8     6.5     6.2
Paul            37     183     Western    16.4    15.3     9.3     8.7
Bam             25     206     Eastern    18.7    19.2     5.1     5.5
Simmons         26     208     Eastern    14.3    13.9     8.0     7.7

#### 3) height 190이상이고 21년 평균득점 값이 30 이상인 농구선수를 추출하는 코드를 작성하시오

In [53]:
people[people["height"] >= 190],[people["ppg_21"]>=30]

(               age  height team_region  ppg_20  ppg_21  apg_20  apg_21
 Lebron          38     206     Western    25.3    26.2    10.2     9.8
 Durant          34     208     Eastern    26.0    27.1     5.9     6.2
 Curry           34     191     Western    32.0    31.0     5.8     6.1
 Harden          33     196     Eastern    24.6    23.4    10.9     9.7
 Westbrook       34     191     Eastern    22.2    21.9    11.7    11.5
 Lillard         32     191     Western    28.8    27.7     7.8     7.5
 Antetokounmpo   28     211     Eastern    28.1    29.0     5.6     5.9
 Jokic           27     213     Western    26.4    26.9     8.3     8.8
 Doncic          23     201     Western    27.7    28.6     8.6     9.0
 Embiid          28     213     Eastern    28.5    28.9     3.0     3.1
 George          32     203     Western    23.3    24.5     5.2     5.4
 Tatum           24     203     Eastern    26.4    25.7     4.3     4.6
 Butler          32     201     Eastern    21.5    22.1     6.0 

#### 4) 선수들의 나이, 키, 평균득점, 어시스트의 평균을 계산해봅시다. 

Hint: `drop`과 `mean` method를 사용합니다. 

In [57]:
people.drop

<bound method DataFrame.drop of                age  height team_region  ppg_20  ppg_21  apg_20  apg_21
Lebron          38     206     Western    25.3    26.2    10.2     9.8
Durant          34     208     Eastern    26.0    27.1     5.9     6.2
Curry           34     191     Western    32.0    31.0     5.8     6.1
Harden          33     196     Eastern    24.6    23.4    10.9     9.7
Westbrook       34     191     Eastern    22.2    21.9    11.7    11.5
Lillard         32     191     Western    28.8    27.7     7.8     7.5
Antetokounmpo   28     211     Eastern    28.1    29.0     5.6     5.9
Jokic           27     213     Western    26.4    26.9     8.3     8.8
Irving          30     188     Eastern    27.0    26.3     6.1     5.9
Doncic          23     201     Western    27.7    28.6     8.6     9.0
Embiid          28     213     Eastern    28.5    28.9     3.0     3.1
George          32     203     Western    23.3    24.5     5.2     5.4
Tatum           24     203     Eastern    26.

In [58]:
people.mean()

C:\Users\joppu\AppData\Local\Temp\ipykernel_18912\3915517147.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  people.mean()


age        29.850
height    200.600
ppg_20     24.175
ppg_21     24.170
apg_20      6.755
apg_21      6.760
dtype: float64

#### 5) 선수들을 소속팀 지역(서부/동부) 지역별로 그룹화 하고, 각 그룹별 나이, 키, 평균득점, 어시스트의 평균을 계산하여 데이터프레임으로 나타내시오

#### 6) 아래는 한 데이터분석가가 NBA 선수의 가치를 평가하기 위해 구축한 함수입니다. 해당 함수를 적용해서, NBA 선수들의 가치를 정량화하여 'value'라는 컬럼을 생성해 봅시다.

(avg_ppg와 avg_apg는 20년과 21년의 평균을 사용합니다) 

In [59]:
def player_value(age, height, avg_ppg, avg_apg):
    value = -0.5 * age + 0.1 * height + 0.5 * avg_ppg + 0.4 * avg_apg
    return value

In [60]:
value

NameError: name 'value' is not defined